# .github/workflows/gradle-build-pr.yml
name: Run Gradle on PRs
on: [push,workflow_dispatch,pull_request]
jobs:
  gradle:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 11
      - uses: eskatos/gradle-command-action@v1
        env:
          CI: true
        with:
            arguments: build
            wrapper-directory: gradle/wrapper
      - uses: example/action-that-comments-on-the-pr@v0
        if: failure()
        with:
          comment: Build failed ${{ steps.gradle.outputs.build-scan-url }}
      - name: build with gradle
        run: |
          gradle clean
          gradle build
      - uses: actions/upload-artifact@v2
        with:
          title: my-artifacts
            - files: [ path/to/artifact.tar.gz ]
            - name: "Packages"
              files: [ umail-web/umail-api/build/libs/,  umail-web/umail-usage/build/libs/ ]
            - name: "Docs"
              files: [ "README.md", doc/screenshots/, doc/*/md ]
          name: umail-usage
          path: |
            umail-web/umail-api/build/libs/
            umail-web/umail-usage/build/libs/
            doc/screenshots/
            doc/*/md
  yarn:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: |
          cd umail-web
          yarn
          yarn build
      - uses: actions/upload-artifact@master
        with:
          name: umail-web
          path: umail-web/dist/
